### ISSUE TITLE
Bind keyword

### ISSUE THREAD

**Issue by jainaman224** [malikankit/city_react_app#1]
`Bind` is used to create a new function(bounded function) that has `this` value.
I think when we try to establish analogy with Java. It creates a new function associated to object rather than `static` method.
[Mozilla doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)

**Comment by hardeeksharma** [comment]
I think it is done because class methods don't automatically bind with the object. So we need to give them the object to which they can bind and access the props object, and there is a scope issue with the functions in java script. [React Docs](https://facebook.github.io/react/docs/handling-events.html)

**Comment by jainaman224** [comment]
Yes, they are either 'constructor` or `prototypical` or `static` methods in ES6 classes. [docs](http://2ality.com/2015/02/es6-classes-final.html)

**Comment by malikankit** [comment]
> I think it is done because class methods don't automatically bind with the object. 
👍 

#JSLessons for everyone today - 
ES6 classes "look like" Java/C++ classes, but don't behave like them. :) 

An over-simplified version of what's happening with our onClick code. 

`ankitmalik@MBP:~|⇒  node
> var an_object = {a:1, printMe(){console.log(this.a);}}
undefined
> var onclick = an_object.printMe;
undefined
> an_object.printMe();
1
undefined
> onclick;
[Function: printMe]
> onclick();
undefined
undefined
> onclick.bind(an_object)();
1
undefined
>`

**Comment by nihalC07** [comment]
> var an_object = {a:1, printMe(){console.log(this.a);}}
undefined
var onclick = an_object.printMe;
undefined
an_object.printMe();
1
undefined
onclick;
[Function: printMe]
onclick();
undefined
undefined
onclick.bind(an_object)();
1
undefined

The above mentioned example refers to directly creating an object, while the classes in ES6 creates `prototypical` functions that get used by various instances we create in it's image. While the example given shows the binding in js, the way this works with classes and thereof in the constructor functions that it gets transpiled to in ES5 may be different.
Kindly help out with the working of bind in [Gist](https://gist.github.com/nihalC07/5b6b0c155ab98fd74e7de6624c6b7dc6).

**Comment by malikankit** [comment]
Yup. That's why the prefix - over-simplified! :)

**Comment by jainaman224** [comment]
@malikankit I also want to know how will this work with `prototypical` and/or `static` functions as I am not able to understand how the analogy work. It would be great if you could help us understand this.

**Comment by nihalC07** [comment]
[React docs : Event Handling](https://facebook.github.io/react/docs/handling-events.html)
This might be it. The bind here has to do with the call back and according to the docs you should bind it one way or the other because you refer to a function without actually calling it in code. The docs explanation consistent with the example @malikankit shared too.

Explanation in docs : 
> You have to be careful about the meaning of this in JSX callbacks. In JavaScript, class methods are not bound by default. If you forget to bind this.handleClick and pass it to onClick, this will be undefined when the function is actually called. This is not React-specific behavior; it is a part of how functions work in JavaScript. Generally, if you refer to a method without () after it, such as onClick={this.handleClick}, you should bind that method.
